### ISSUE TITLE
AoT compilation still broken

### ISSUE THREAD

**Issue by aleesaan** [w11k/angular-sticky-things#7]
Hi again, I see the last commit reverted the fix I pushed in my last [PR](https://github.com/w11k/angular-sticky-things/pull/5), I'm not sure what happened. Could you have a look?

**Comment by CanKattwinkel** [comment]
Oh, I think I played myself.. At first, I was too fast with merging your Pull-Request since it was going into the master and this repo is following Git Flow where commits should be going into the develop branch. 

Then I cleaned the master via gui and unfixed it during the local merge. Sorry about that but on npm there is the correct version. I'll create an hotfix cleaning up the gitty thingy. ;)

**Comment by CanKattwinkel** [comment]
Due to the small time window, I allowed myself a force push with the fixed merge. Repo should now represent the state on npm, sorry for the inconvenience!
